FROM python:3.11-slim

WORKDIR /app

RUN pip install fastapi uvicorn azure-servicebus opencensus-ext-azure opencensus-ext-logging

COPY api/main.py .

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
